status: 0
name: Runtime errors should emit hygienic errors if possible
asserts:
  - source: fg.err.log
    contains:
      - "10 | select event.foo_select from in"
      - "   |              ^^^^^^^^^^ Trying to access a non existing event key `foo_select`"
      - "11 | where event.foo_where == true"
      - "   |             ^^^^^^^^^ Trying to access a non existing event key `foo_where`"
      - "12 | group by event.foo_group"
      - "   |                ^^^^^^^^^ Trying to access a non existing event key `foo_group`"
      - "13 | into runtime having event[\"foo_having\"] == true;"
      - "   |                           ^^^^^^^^^^^^ Trying to access a non existing event key `foo_having`"
  - source: events.log
    equals_file: "expected.json"
